stages:
  - deploy

# Основная задача для синхронизации
sync_to_github:
  stage: deploy
  before_script:
    - echo "Начинаем синхронизацию с GitHub"
  script:
    - git config --global user.name "gitflic-bot"
    - git config --global user.email "bot@gitflic.ru"
    - git remote add github https://s-evg:${GITHUB_SYNC}@github.com/s-evg/CoLearn.git
    - git push github --all
    - git push github --tags
  after_script:
    - echo "Синхронизация завершена"
  only:
    - branches

end_job:
  stage: deploy
  script:
    echo OK

