name: Sync Repo and Wiki to GitFlic

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git for Repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add GitFlic remote for Repo
        run: git remote add gitflic https://s-evg:${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/project/s-evg/colearn.git

      - name: Push Repo to GitFlic
        run: |
          git push gitflic --all
          git push gitflic --tags

      - name: Checkout Wiki repository
        uses: actions/checkout@v3
        with:
          repository: s-evg/CoLearn.wiki
          path: wiki
          fetch-depth: 0

      - name: Set up Git for Wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add GitFlic remote for Wiki
        run: |
          cd wiki
          git remote add gitflic https://s-evg:${{ secrets.GITFLIC_WIKI }}@gitflic.ru/project/s-evg/colearn.wiki.git

      - name: Push Wiki to GitFlic
        run: |
          cd wiki
          git push gitflic --all
          git push gitflic --tags
